### ISSUE TITLE
有考虑支持lark吗

### ISSUE THREAD

**Issue by qiuyueovo** [flydoos/FeiShuRevokeMsgPatcher#1]
佬，有考虑支持lark吗。还是飞书和lark都支持。
lark是海外版的飞书。原理应该都一样。

**Comment by flydoos** [comment]
对了，之前的 1.0.0 版本，打包的时候漏了一个DLL导致无法使用，已经重新上传，你需要重新下载一下

**Comment by qiuyueovo** [comment]
> 对了，之前的 1.0.0 版本，打包的时候漏了一个DLL导致无法使用，已经重新上传，你需要重新下载一下

可以的

**Comment by qiuyueovo** [comment]
> > 佬，有考虑支持lark吗。还是飞书和lark都支持。 lark是海外版的飞书。原理应该都一样。
> 
> 学习了，原来lark是海外版飞书，怪不得分析的时候总是看到这个单词。
> 
> 做应该是能做的，毕竟都是差不多的东西，但是难的并不是做，而是持续更新，我之前维护钉钉消息防撤回补丁，每个月更新好几次，非常累的。飞书这个也是坑爹，我上周通宵研究的时候是7.13.8，好不容易弄出来了，前几天又升级到7.14.4，更新如此频繁，不适合再搞新的，先把这个国内版做好再说，其他暂不考虑

或者可以提供思路给我们？之前没有了解过这方面。飞书小版本会有，大版本基本上一个月也才会更新一次

**Comment by flydoos** [comment]
每个版本的特征码都是不一样的，只要更新，补丁就要更新……大版本的话，可能还会改的面目全非，全部都要重新分析，反正是纯体力活……

**Comment by qiuyueovo** [comment]
> 每个版本的特征码都是不一样的，只要更新，补丁就要更新……大版本的话，可能还会改的面目全非，全部都要重新分析，反正是纯体力活……

这个确实。可惜我不会这方面的，不然可以帮你弄一下。
