### ISSUE TITLE
飞书打开异常

### ISSUE THREAD

**Issue by qiuyueovo** [flydoos/FeiShuRevokeMsgPatcher#2]
![image](https://github.com/flydoos/FeiShuRevokeMsgPatcher/assets/40270698/6b9d485f-4b04-4d14-9aac-cd5fa9a7124a)
如图所示：飞书版本是最新的。我有两个租户，其中一个租户打开正常并且可以防撤回，而另外一个租户不行。

lark原理应该和飞书的一样。感觉都可以实现。

**Comment by flydoos** [comment]
你这个是飞书什么版本？到底是飞书，还是lark？
建议你重装飞书之后，重新打补丁试试，如果还是不行，请加QQ群：390669197，联系群主处理

**Comment by qiuyueovo** [comment]
我用的飞书。
版本号：7.14.4。

**Comment by qiuyueovo** [comment]
消息加载较多，清理缓存重新加载后恢复正常。待观察

**Comment by flydoos** [comment]
此问题已在 1.1.2 版本的飞书补丁中修复，修复部分用户通讯录界面显示白屏问题
