### ISSUE TITLE
[Feature request]: 支持消息永不已读

### ISSUE THREAD

**Issue by Kukuair** [flydoos/FeiShuRevokeMsgPatcher#4]
您好，之前用了[DingTalkRevokeMsgPatcher](https://github.com/flydoos/DingTalkRevokeMsgPatcher)，其中的 支持消息永不已读功能 可以在[FeiShuRevokeMsgPatcher](https://github.com/flydoos/FeiShuRevokeMsgPatcher)上实现吗

**Comment by flydoos** [comment]
> 您好，之前用了[DingTalkRevokeMsgPatcher](https://github.com/flydoos/DingTalkRevokeMsgPatcher)，其中的 支持消息永不已读功能 可以在[FeiShuRevokeMsgPatcher](https://github.com/flydoos/FeiShuRevokeMsgPatcher)上实现吗

 我也希望有这个功能，但是目前来说，不乐观，飞书这个比钉钉的难搞太多了，主要是因为两者的消息机制不一样，飞书还会强制销毁旧消息。
目前，连图片消息防撤回都还搞不定，消息永不已读，短期内应该都不会有的，持续关注补丁吧

**Comment by flydoos** [comment]
> 您好，之前用了[DingTalkRevokeMsgPatcher](https://github.com/flydoos/DingTalkRevokeMsgPatcher)，其中的 支持消息永不已读功能 可以在[FeiShuRevokeMsgPatcher](https://github.com/flydoos/FeiShuRevokeMsgPatcher)上实现吗

如无意外，明天会发布飞书的“永不已读”功能，敬请期待

**Comment by Kukuair** [comment]
果然是 牛A与牛C之间  👍
