### ISSUE TITLE
7.19.4 可以支持下吗

### ISSUE THREAD

**Issue by jojoecfy** [flydoos/FeiShuRevokeMsgPatcher#6]
RT

**Comment by flydoos** [comment]
![20240530152442](https://github.com/flydoos/FeiShuRevokeMsgPatcher/assets/3932827/b81679b2-e1da-4925-aa54-ba1128241a69)
只看到 7.19.2 没有你说的 7.19.4，今晚20：00之前会更新 7.19.2

**Comment by jojoecfy** [comment]
![image](https://github.com/flydoos/FeiShuRevokeMsgPatcher/assets/45198487/3cc1cffd-9a02-47ce-92aa-0bd023e3a360)
我这里是windows版本 自动更新的，如果还是看不到我就等后续的更新吧

**Comment by flydoos** [comment]
看来飞书也是灰度发布的，如果是这样，那就只有你提供安装包给我才行了，自动更新的安装包路径，放在这里：
C:\Users\改成你的用户名\AppData\Roaming\LarkShell\update\update_downloading
你把里面的exe文件上传给我下载即可（不要传百度网盘啊）

**Comment by jojoecfy** [comment]
https://www.123pan.com/s/t8moTd-oEOid.html提取码:K3we

**Comment by flydoos** [comment]
> [https://www.123pan.com/s/t8moTd-oEOid.html提取码:K3we](https://www.123pan.com/s/t8moTd-oEOid.html%E6%8F%90%E5%8F%96%E7%A0%81:K3we) 这种可以吗 辛苦大佬

可以，今晚会抽空看看，可能要明天才能发布，耐心等待

**Comment by flydoos** [comment]
更新至 2.2.0，支持飞书 7.19.2 版本、7.19.4 版本
https://www.wuleba.com/?p=2610
